[project]
name = "g1"
version = "0.1.0"
description = "Gradio Tutorial 1"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asyncio>=3.4.3",
    "gradio>=5.16.0",
    "huggingface-hub>=0.28.1",
    "jokeapi>=0.2.2",
    "pillow>=11.1.0",
    "python-dotenv>=1.0.1",
    "qrcode>=8.0",
    "requests>=2.32.3",
    "rich>=13.9.4",
    "simplejson>=3.19.3",
]
